mode: 'test' 
object: 'image'
save_dir: 'save/save_test/'

pretrained: True # backbone是否用ImageNet预训练的权重
load_checkpoint: True
resume: '/home/lpy/project/myproject/save/srm_adamw/ckpt_srm_resnet50_epoch_4_0.90557.pth'
manual_seed: 43

batch_size: 256
print_freq: 10
threshold: 0.5 

dataset:
  name: 'FF_face'
  FF_face:
    val_data_path: '/raid/lpy/data/FaceForensics++/annotations/ff_baseline/test_shuffle.txt'
    image_size: 256
    transform: 'resize'
  FF_dir:
    data_dir: '/raid/lpy/data/FaceForensics++/'
    split_dir : '/raid/lpy/data/FaceForensics++/splits/'
    frame_dir : '/raid/lpy/data/FaceForensics++/method/c23/frames_64/' # 最后一定要有/
    bbox_name : 'bbox_64_1.5'
    image_size: 256
    num_frames: 50
    transform: 'resize'
  CDF_img:
    val_data_path: ''
    image_size: 256
    transform: 'normal'
  small:
    val_data_path: '/raid/lpy/data/my_annotations/small_val.txt'
    image_size: 256
    transform: 'resize'

model:
  name: 'srm' # 'resnet' # 'base_net'
  

backbone:
  name: 'resnet50'
  resnet50:
    drop_rate: 0.2

opt:
  name: 'adamw'
  adamw:
    lr: 2.0e-4 # 1e-3 # 2.0e-4 
    weight_decay: 1.0e-5 # 0.02 # 1.0e-5
  adam:
    lr: 1.0e-3
    betas1: 0.9
    betas2: 0.999
    eps: 1.0e-8
    weight_decay: 0
  SGD:
    lr: 1.0e-4
    momentum: 0.9
    decay: 1.0e-6

sched:
  name: 'StepLR'
  MultiStepLR:
    milestones: [3, 6, 10, 15, 20]
    gamma: 0.2
  StepLR:
    step_size: 2
    gamma: 0.6
criterion: 'CE' # 'CE','BCE'


