mode: 'test' 
object: 'image'
pretrained: True # backbone是否用ImageNet预训练的权重
load_checkpoint: True
resume: '/home/lpy/project/myproject/save_res50/ckpt_epoch_3_0.92560839263137.pth'
manual_seed: 43

batch_size: 128
print_freq: 10
threshold: 0.5 

dataset:
  name: 'FF_img'
  FF_img:
    val_data_path: '/raid/lpy/data/FaceForensics++/annotations/ff_baseline/test_shuffle.txt'
    image_size: 256
    transform: 'resize'
  CDF_img:
    val_data_path: ''
    image_size: 256
    transform: 'normal'
  small:
    val_data_path: '/raid/lpy/data/my_annotations/small_val.txt'
    image_size: 256
    transform: 'resize'

model:
  name: 'base_net'
  

backbone:
  name: 'resnet50'
  resnet50:
    drop_rate: 0.2

opt:
  name: 'adamw'
  adamw:
    lr: 2.0e-4
    weight_decay: 1.0e-5

sched:
  name: 'MultiStepLR'
  MultiStepLR:
    milestones: [3, 6, 10, 15, 20]
    gamma: 0.2

criterion: 'CE'



